apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    release: "10.4"
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: xldadministrator
  POSTGRES_PASSWORD: mysecretpassword
  #PGDATA: /var/lib/postgresql/data/data
