apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    release: "10.4"
spec:
  type: LoadBalancer
  ports:
   - port: 5432
  selector:
   app: postgres
   release: "10.4"
