kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-11
  labels:
    app: postgres
    release: "10.4"
spec:
  #storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi