apiVersion: v1
kind: ConfigMap
metadata:
  name: xldeploy-config
  labels:
    app: xldeploy
    release: "8.2.1"
data:
  ADMIN_PASSWORD: admin
  JDBC_USERNAME: xldadministrator
  JDBC_PASSWORD: mysecretpassword
  JDBC_URL: jdbc:postgresql://postgres:5432/postgres
  JDBC_DRIVER: org.postgresql.Driver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xld-pv-claim-configuration
  labels:
    app: xldeploy
    release: "8.2.1"
spec:
  #storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xldeploy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xldeploy
      release: "8.2.1"
  template:
    metadata:
      labels:
        app: xldeploy
        release: "8.2.1"
    spec:
      containers:
      - name: xldeploy
        image: bmoussaud/xl-deploy-with-db:8.2.7
        imagePullPolicy: Always
        ports:
        - name: xld-http
          containerPort: 4516
          protocol: TCP
        volumeMounts:
          - name: xldeploy-storage-configuration
            mountPath: /opt/xebialabs/xl-deploy-server/ext
        livenessProbe:
            httpGet:
              path: /
              port: xld-http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 12
        readinessProbe:
            httpGet:
              path: /
              port: xld-http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 12
        envFrom:
            - configMapRef:
                name: xldeploy-config
      volumes:
        - name: xldeploy-storage-configuration
          persistentVolumeClaim:
            claimName: xld-pv-claim-configuration
---
apiVersion: v1
kind: Service
metadata:
  name: xld-service
  labels:
    app: xldeploy
    release: "8.2.1"
spec:
  type: LoadBalancer
  ports:
    - port: 4516
      targetPort: xld-http
      protocol: TCP
      name: xld-http-svc
  selector:
    app: xldeploy
    release: "8.2.1"
