apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xld-pv-claim-conf
  labels:
    app: xldeploy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xld-pv-claim-ext
  labels:
    app: xldeploy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi