apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xld-pv-claim-configuration
  labels:
    app: xldeploy
    release: "8.2.1"
spec:
  #storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
