apiVersion: v1
kind: Service
metadata:
  name: xld-service
  labels:
    app: xldeploy
    release: "8.2.1"
spec:
  type: LoadBalancer
  ports:
    - port: 4516
      targetPort: xld-http
      protocol: TCP
      name: xld-http-svc
  selector:
    app: xldeploy
    release: "8.2.1"
