apiVersion: apps/v1
kind: Deployment
metadata:
  name: xldeploy-deployment
  labels:
    app: xldeploy
    release: 8.2.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xldeploy
      release: 8.2.1
  template:
    metadata:
      labels:
        app: xldeploy
        release: 8.2.1
    spec:
      containers:
      - name: xldeploy
        image: bmoussaud/xl-deploy-with-db:8.2.1
        imagePullPolicy: Always
        ports:
        - name: xld-http
          containerPort: 4516
          protocol: TCP
        livenessProbe:
            httpGet:
              path: /
              port: xld-http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 12
        readinessProbe:
            httpGet:
              path: /
              port: xld-http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 12
        envFrom:
            - configMapRef:
                name: xldeploy-config
        securityContext:
            runAsUser: 1001
            runAsGroup: 1001
